// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayers.Repository.DbContexts;

#nullable disable

namespace NLayers.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231231102719_databaseComplated")]
    partial class databaseComplated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CertificateEntityUserEntity", b =>
                {
                    b.Property<int>("CertificatesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CertificatesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CertificateEntityUserEntity");
                });

            modelBuilder.Entity("CompanyInfoEntityCompanyUserRoleEntity", b =>
                {
                    b.Property<int>("CompanyInfosId")
                        .HasColumnType("int");

                    b.Property<int>("UserRolesId")
                        .HasColumnType("int");

                    b.HasKey("CompanyInfosId", "UserRolesId");

                    b.HasIndex("UserRolesId");

                    b.ToTable("CompanyInfoEntityCompanyUserRoleEntity");
                });

            modelBuilder.Entity("CompanyInfoEntityUserEntity", b =>
                {
                    b.Property<int>("CompanyInfosId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CompanyInfosId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyInfoEntityUserEntity");
                });

            modelBuilder.Entity("KnownProgramEntityUserEntity", b =>
                {
                    b.Property<int>("KnownProgramsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("KnownProgramsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("KnownProgramEntityUserEntity");
                });

            modelBuilder.Entity("NLayers.Core.Entities.CertificateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CertificateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CertificatesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateDescription = "Test",
                            CertificateName = "Test1",
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3155),
                            FileName = "Test",
                            FilePath = "Test",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificateDescription = "Test",
                            CertificateName = "Test2",
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3157),
                            FileName = "Test",
                            FilePath = "Test",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CertificateDescription = "Test",
                            CertificateName = "Test3",
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3158),
                            FileName = "Test",
                            FilePath = "Test",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CertificateDescription = "Test",
                            CertificateName = "Test4",
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3159),
                            FileName = "Test",
                            FilePath = "Test",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CertificateDescription = "Test",
                            CertificateName = "Test5",
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3160),
                            FileName = "Test",
                            FilePath = "Test",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.CompanyInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyInfoTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyAddress = "Test1",
                            CompanyDescription = "Test1",
                            CompanyField = "Test1",
                            CompanyName = "Test1",
                            FileName = "Test1",
                            FilePath = "Test1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyAddress = "Test2",
                            CompanyDescription = "Test2",
                            CompanyField = "Test2",
                            CompanyName = "Test2",
                            FileName = "Test2",
                            FilePath = "Test2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyAddress = "Test3",
                            CompanyDescription = "Test3",
                            CompanyField = "Test3",
                            CompanyName = "Test3",
                            FileName = "Test3",
                            FilePath = "Test3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanyAddress = "Test4",
                            CompanyDescription = "Test4",
                            CompanyField = "Test4",
                            CompanyName = "Test4",
                            FileName = "Test4",
                            FilePath = "Test4",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CompanyAddress = "Test5",
                            CompanyDescription = "Test5",
                            CompanyField = "Test5",
                            CompanyName = "Test5",
                            FileName = "Test5",
                            FilePath = "Test5",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.CompanyUserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CompanyInfosId")
                        .HasColumnType("int");

                    b.Property<string>("UserRoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyUserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyInfosId = 1,
                            UserRoleDescription = "Test1",
                            UserRoleName = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            CompanyInfosId = 5,
                            UserRoleDescription = "Test2",
                            UserRoleName = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            CompanyInfosId = 5,
                            UserRoleDescription = "Test3",
                            UserRoleName = "Test3"
                        },
                        new
                        {
                            Id = 4,
                            CompanyInfosId = 4,
                            UserRoleDescription = "Test4",
                            UserRoleName = "Test4"
                        },
                        new
                        {
                            Id = 5,
                            CompanyInfosId = 4,
                            UserRoleDescription = "Test5",
                            UserRoleName = "Test5"
                        },
                        new
                        {
                            Id = 6,
                            CompanyInfosId = 1,
                            UserRoleDescription = "Test6",
                            UserRoleName = "Test6"
                        },
                        new
                        {
                            Id = 7,
                            UserRoleDescription = "Test7",
                            UserRoleName = "Test7"
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.KnownProgramEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KnownProgramTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProgramDescription = "Test1",
                            ProgramName = "Test1",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProgramDescription = "Test2",
                            ProgramName = "Test2",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ProgramDescription = "Test3",
                            ProgramName = "Test3",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.SchoolDepartmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchoolDepartmentTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentDescription = "Test1",
                            DepartmentName = "Test1",
                            SchoolsId = 2
                        },
                        new
                        {
                            Id = 2,
                            DepartmentDescription = "Test2",
                            DepartmentName = "Test2",
                            SchoolsId = 3
                        },
                        new
                        {
                            Id = 3,
                            DepartmentDescription = "Test3",
                            DepartmentName = "Test3",
                            SchoolsId = 1
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.SchoolInformationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchoolInformationTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Test1",
                            SchoolDescription = "Test1",
                            SchoolName = "Test1",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Location = "Test2",
                            SchoolDescription = "Test2",
                            SchoolName = "Test2",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Location = "Test3",
                            SchoolDescription = "Test3",
                            SchoolName = "Test3",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.SpeakingLanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpeakingLanguagesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageDescription = "Test1",
                            LanguageName = "Test1",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            LanguageDescription = "Test2",
                            LanguageName = "Test2",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            LanguageDescription = "Test3",
                            LanguageName = "Test3",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserAdressEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAdressTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Ankara/Sincan",
                            Country = "Türkiye",
                            PostalCode = "12345",
                            State = "A Mah",
                            StreetName = "12345"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Ankara/Yenimahalle",
                            Country = "Türkiye",
                            PostalCode = "12345",
                            State = "B Mah",
                            StreetName = "12345"
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Ankara/Ostim",
                            Country = "Türkiye",
                            PostalCode = "12345",
                            State = "C Mah",
                            StreetName = "12345"
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UsersTable");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3039),
                            Email = "AdminEmail@email.com",
                            FirstName = "AdminName",
                            LastName = "AdminLastName",
                            Password = "Admin",
                            PhoneNumber = "AdminPhoneNumber",
                            Roles = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3052),
                            Email = "Email1@email.com",
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Password = "Password1",
                            PhoneNumber = "PhoneNumber1",
                            Roles = "User"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2023, 12, 31, 13, 27, 18, 871, DateTimeKind.Local).AddTicks(3053),
                            Email = "Email2@email.com",
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Password = "Password2",
                            PhoneNumber = "PhoneNumber2",
                            Roles = "User"
                        });
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserInformationEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirtDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MSwasDone")
                        .HasColumnType("bit");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInformationTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirtDay = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Hobies = "Hobies A",
                            MSwasDone = true,
                            UserDescription = "Description A"
                        },
                        new
                        {
                            Id = 2,
                            BirtDay = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Hobies = "Hobies b",
                            MSwasDone = true,
                            UserDescription = "Description b"
                        },
                        new
                        {
                            Id = 3,
                            BirtDay = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Hobies = "Hobies c",
                            MSwasDone = true,
                            UserDescription = "Description c"
                        });
                });

            modelBuilder.Entity("SchoolDepartmentEntitySchoolInformationEntity", b =>
                {
                    b.Property<int>("SchoolsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentDepartmentsId")
                        .HasColumnType("int");

                    b.HasKey("SchoolsId", "StudentDepartmentsId");

                    b.HasIndex("StudentDepartmentsId");

                    b.ToTable("SchoolDepartmentEntitySchoolInformationEntity");
                });

            modelBuilder.Entity("SchoolInformationEntityUserEntity", b =>
                {
                    b.Property<int>("SchoolInfosId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SchoolInfosId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolInformationEntityUserEntity");
                });

            modelBuilder.Entity("SpeakingLanguageEntityUserEntity", b =>
                {
                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LanguagesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SpeakingLanguageEntityUserEntity");
                });

            modelBuilder.Entity("CertificateEntityUserEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.CertificateEntity", null)
                        .WithMany()
                        .HasForeignKey("CertificatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyInfoEntityCompanyUserRoleEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.CompanyInfoEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyInfosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.CompanyUserRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyInfoEntityUserEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.CompanyInfoEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanyInfosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnownProgramEntityUserEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.KnownProgramEntity", null)
                        .WithMany()
                        .HasForeignKey("KnownProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserAdressEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.UserEntity", "User")
                        .WithOne("UserAdress")
                        .HasForeignKey("NLayers.Core.Entities.UserAdressEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserInformationEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.UserEntity", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("NLayers.Core.Entities.UserInformationEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolDepartmentEntitySchoolInformationEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.SchoolInformationEntity", null)
                        .WithMany()
                        .HasForeignKey("SchoolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.SchoolDepartmentEntity", null)
                        .WithMany()
                        .HasForeignKey("StudentDepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolInformationEntityUserEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.SchoolInformationEntity", null)
                        .WithMany()
                        .HasForeignKey("SchoolInfosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpeakingLanguageEntityUserEntity", b =>
                {
                    b.HasOne("NLayers.Core.Entities.SpeakingLanguageEntity", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NLayers.Core.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NLayers.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("UserAdress")
                        .IsRequired();

                    b.Navigation("UserInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
